<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.mycom.myapp</groupId>
		<artifactId>myapp-base</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>myapp-ng</artifactId>
	<packaging>war</packaging>

	<build>
		<plugins>
			<!-- 1. Node + npm + Angular build -->
			<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>install-node-and-npm</id>
						<!--<phase>generate-resources</phase>-->
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<configuration>
							<workingDirectory>${project.basedir}/ng</workingDirectory>
							<nodeVersion>v24.16.0</nodeVersion>
							<npmVersion>11.16.0</npmVersion>
						</configuration>
					</execution>
					<execution>
						<id>npm-install</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<workingDirectory>${project.basedir}/ng</workingDirectory>
							<arguments>install --legacy-peer-deps</arguments>
						</configuration>
					</execution>
					<execution>
						<id>npm build</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<phase>generate-resources</phase>
						<configuration>
							<workingDirectory>${project.basedir}/ng</workingDirectory>
							<arguments>run build</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.3.1</version>
				<executions>
					<execution>
						<id>copy-angular-to-war</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>
								${project.build.directory}/${project.build.finalName}/myapp/ng</outputDirectory>
							<resources>
								<resource>
									<directory>dist/myapp-ng/browser</directory>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<!-- 2. Package Angular dist/myapp-ng/browser into WAR root -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<!-- Folder that contains index.html -->
					<warSourceDirectory>
						${project.basedir}/ng/dist/myapp-ng/browser</warSourceDirectory>
					<failOnMissingWebXml>false</failOnMissingWebXml>
					<webResources>
						<resource>
							<directory>
								${project.basedir}/ng/dist/myapp-ng/browser</directory>
							<includes>
								<include>**/*.*</include>
							</includes>
						</resource>
					</webResources>
				</configuration>
			</plugin>

		</plugins>
	</build>

</project>
